### ISSUE TITLE
Invalid config for S2_Download DAG

### ISSUE THREAD

**Issue by ricardogsilva** [geosolutions-it/evo-odas#160]
Just trying to get airflow up and running throws the error:

```python
ERROR - Failed to import: /usr/local/evoodas/geosolutions/airflow/dags/sentinel2/S2_Download.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 264, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/evoodas/geosolutions/airflow/dags/sentinel2/S2_Download.py", line 98, in <module>
    target_dir = sentinel2_config['product_zip_target_dir'],
KeyError: 'product_zip_target_dir'
```

The module `evo-odas/airflow/dags/sentinel2/config.py` is missing a `sentinel2_config["product_zip_target_dir"] key.

**Comment by randomorder** [comment]
I'll make a PR for this early next week
https://github.com/randomorder/evo-odas/commit/319a12686a444823d0686be2aeff4da88a7b78a5

**Comment by randomorder** [comment]
Fixed by https://github.com/geosolutions-it/evo-odas/pull/163
