### ISSUE TITLE
Fix black outside mosaic in S2 display

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/evo-odas#277]
Right now outside of the data area we get full black tiles.

**Comment by aaime** [comment]
I believe this one has been fixed as part of the recent work done on mosaic (and/or the wip by Daniele on the same topic). Maybe we can contact Torsten to see if the black is still there?

**Comment by torse** [comment]
It seems not be fixed after updating GeoServer (https://oda.dlr.de/geoserver) to

```
    Resource name: GeoServer
        Build-Timestamp : 14-Dec-2017 12:43
        Version : 2.13-SNAPSHOT
        Git-Revision : 13717975c95dd18c67de699284ee79e3e8f8eb10
    Resource name: GeoTools
        Build-Timestamp : 12-Dec-2017 14:54
        Version : 19-SNAPSHOT
        Git-Revision : 1c8c968c838ce37d174357c54c36a4cb7f35a6e5
    Resource name: GeoWebCache
        Version : 1.13-SNAPSHOT
        Git-Revision : 4b806d689fef717899d8456c7b9e35d2c326b6f7/4b806d689fef717899d8456c7b9e35d2c326b6f7
```
It should have picked up https://github.com/geotools/geotools/commit/1c8c968c838ce37d174357c54c36a4cb7f35a6e5 but the black border is still visable on http://oda.dlr.de/eoxclient.

Do I need to update anything else?

**Comment by aaime** [comment]
@torse how is transparency managed in those mosaics? Nodata, footprints?

**Comment by torse** [comment]
@aaime just checked and it is not managed at all, so no wonder that there are black borders. However some parts of the output image are transparent (between the black borders and the actual tiles):
![selection_556](https://user-images.githubusercontent.com/8510931/34147049-a61006ce-e49c-11e7-85b0-4d831f382c1a.png)

Anyway it seems that there is something wrong with the setup: When I change anything in the ``evoodas:S2_MSI_L1C_MOSAIC`` layer (e.g. FootprintBehaviour) and save it, than the following exception is thrown. When coming back to the layer config I can see that the change hasn't been applied.
```
geoserver_1           | 19 Dec 08:09:31 WARN [geoserver.catalog] - Error while getting feature type, flushing cache and retrying: Schema 'LANDSAT8__B1' does not exist.
geoserver_1           | 19 Dec 08:09:31 WARN [geoserver.catalog] - Unable to flush 'http://evoodas:LANDSAT8__B1
geoserver_1           | java.io.IOException: Schema 'LANDSAT8__B1' does not exist.
geoserver_1           | 	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:620)
geoserver_1           | 	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:393)
geoserver_1           | 	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:360)
geoserver_1           | 	at org.geoserver.catalog.ResourcePool.flushState(ResourcePool.java:2623)
geoserver_1           | 	at org.geoserver.catalog.ResourcePool.flushDataStore(ResourcePool.java:2597)
geoserver_1           | 	at org.geoserver.catalog.ResourcePool.getFeatureType(ResourcePool.java:942)
geoserver_1           | 	at org.geoserver.catalog.ResourcePool.getFeatureType(ResourcePool.java:930)
geoserver_1           | 	at org.geoserver.catalog.impl.FeatureTypeInfoImpl.getFeatureType(FeatureTypeInfoImpl.java:121)
geoserver_1           | 	at sun.reflect.GeneratedMethodAccessor355.invoke(Unknown Source)
geoserver_1           | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
geoserver_1           | 	at java.lang.reflect.Method.invoke(Method.java:498)
geoserver_1           | 	at org.geoserver.catalog.impl.ModificationProxy.invoke(ModificationProxy.java:147)
geoserver_1           | 	at com.sun.proxy.$Proxy33.getFeatureType(Unknown Source)
geoserver_1           | 	at org.geoserver.web.CatalogIconFactory.getSpecificLayerIcon(CatalogIconFactory.java:121)
geoserver_1           | 	at org.geoserver.web.data.layer.LayerPage$1.getComponentForProperty(LayerPage.java:59)
geoserver_1           | 	at org.geoserver.web.wicket.GeoServerTablePanel$5.populateItem(GeoServerTablePanel.java:232)
geoserver_1           | 	at org.apache.wicket.markup.html.list.ListView.onPopulate(ListView.java:523)
geoserver_1           | 	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:124)
geoserver_1           | 	at org.apache.wicket.Component.internalBeforeRender(Component.java:950)
geoserver_1           | 	at org.apache.wicket.Component.beforeRender(Component.java:1018)
geoserver_1           | 	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1836)
geoserver_1           | 	at org.apache.wicket.Component.onBeforeRender(Component.java:3916)
geoserver_1           | 	at org.apache.wicket.Component.internalBeforeRender(Component.java:950)
geoserver_1           | 	at org.apache.wicket.Component.beforeRender(Component.java:1018)
geoserver_1           | 	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1836)
geoserver_1           | 	at org.apache.wicket.Component.onBeforeRender(Component.java:3916)
geoserver_1           | 	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:143)
geoserver_1           | 	at org.apache.wicket.markup.repeater.AbstractPageableView.onBeforeRender(AbstractPageableView.java:115)
geoserver_1           | 	at org.apache.wicket.Component.internalBeforeRender(Component.java:950)
geoserver_1           | 	at org.apache.wicket.Component.beforeRender(Component.java:1018)
geoserver_1           | 	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1836)
geoserver_1           | 	at org.apache.wicket.Component.onBeforeRender(Component.java:3916)
geoserver_1           | 	at org.apache.wicket.Component.internalBeforeRender(Component.java:950)
geoserver_1           | 	at org.apache.wicket.Component.beforeRender(Component.java:1018)
geoserver_1           | 	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1836)
geoserver_1           | 	at org.apache.wicket.Component.onBeforeRender(Component.java:3916)
geoserver_1           | 	at org.apache.wicket.Component.internalBeforeRender(Component.java:950)
geoserver_1           | 	at org.apache.wicket.Component.beforeRender(Component.java:1018)
geoserver_1           | 	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1836)
geoserver_1           | 	at org.apache.wicket.Component.onBeforeRender(Component.java:3916)
geoserver_1           | 	at org.apache.wicket.Page.onBeforeRender(Page.java:801)
geoserver_1           | 	at org.apache.wicket.Component.internalBeforeRender(Component.java:950)
geoserver_1           | 	at org.apache.wicket.Component.beforeRender(Component.java:1018)
geoserver_1           | 	at org.apache.wicket.Component.internalPrepareForRender(Component.java:2236)
geoserver_1           | 	at org.apache.wicket.Page.internalPrepareForRender(Page.java:242)
geoserver_1           | 	at org.apache.wicket.Component.render(Component.java:2325)
geoserver_1           | 	at org.apache.wicket.Page.renderPage(Page.java:1018)
geoserver_1           | 	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
geoserver_1           | 	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
geoserver_1           | 	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
geoserver_1           | 	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
geoserver_1           | 	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
geoserver_1           | 	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
geoserver_1           | 	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
geoserver_1           | 	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
geoserver_1           | 	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
geoserver_1           | 	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
geoserver_1           | 	at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
geoserver_1           | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
geoserver_1           | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
geoserver_1           | 	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:157)
geoserver_1           | 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
geoserver_1           | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
geoserver_1           | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
geoserver_1           | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
geoserver_1           | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
geoserver_1           | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
geoserver_1           | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
geoserver_1           | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
geoserver_1           | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
geoserver_1           | 	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
geoserver_1           | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
geoserver_1           | 	at org.geoserver.opensearch.eo.OSEOFilter.doFilter(OSEOFilter.java:41)
geoserver_1           | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
geoserver_1           | 	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:94)
geoserver_1           | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
geoserver_1           | 	at org.geoserver.flow.ControlFlowCallback.doFilter(ControlFlowCallback.java:245)
geoserver_1           | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
geoserver_1           | 	at org.geoserver.params.extractor.Filter.doFilter(Filter.java:46)
geoserver_1           | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
geoserver_1           | 	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
geoserver_1           | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
geoserver_1           | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
geoserver_1           | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
geoserver_1           | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerUserNamePasswordAuthenticationFilter.doFilter(GeoServerUserNamePasswordAuthenticationFilter.java:116)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
geoserver_1           | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:213)
geoserver_1           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:84)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
geoserver_1           | 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:157)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerRoleFilter.doFilter(GeoServerRoleFilter.java:64)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
geoserver_1           | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
geoserver_1           | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
geoserver_1           | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
geoserver_1           | 	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:152)
geoserver_1           | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
geoserver_1           | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:84)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:89)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
geoserver_1           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver_1           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver_1           | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
geoserver_1           | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
geoserver_1           | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
geoserver_1           | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
geoserver_1           | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
geoserver_1           | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
geoserver_1           | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
geoserver_1           | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
geoserver_1           | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
geoserver_1           | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
geoserver_1           | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
geoserver_1           | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
geoserver_1           | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
geoserver_1           | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
geoserver_1           | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
geoserver_1           | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
geoserver_1           | 	at java.lang.Thread.run(Thread.java:745)
geoserver_1           | 19 Dec 08:12:02 WARN [geoserver.ows] - Could not get a ServiceInfo for service oseo thus could not check if the service is enabled
```

**Comment by torse** [comment]
With the geotools updates from Daniele just before christmas, the black border issue is now fixed! Thanks @dromagnoli!

![selection_560](https://user-images.githubusercontent.com/8510931/34720812-756cd2fe-f540-11e7-9e6c-1da6d1c6cb74.png)

The black nondata areas within one granule remains though. Setting the background value or transparent input value doesn't seem to work for me. I guess we need to setup footprint management (e.g. by extracting the footprint during ingestion and generating a WKT sidecar file to the jp2 files)
